[2024-11-16T11:40:10.561+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-16T11:40:10.627+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2024-11-16T11:40:10.680+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2024-11-16T11:40:10.691+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-16T11:40:10.902+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_news> on 2024-11-16 00:00:00+00:00
[2024-11-16T11:40:11.006+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2491) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-16T11:40:11.017+0000] {standard_task_runner.py:72} INFO - Started process 2514 to run task
[2024-11-16T11:40:11.050+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_news', 'scheduled__2024-11-16T00:00:00+00:00', '--job-id', '674', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpq0togh7m']
[2024-11-16T11:40:11.058+0000] {standard_task_runner.py:105} INFO - Job 674: Subtask run_API_news
[2024-11-16T11:40:11.302+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_news scheduled__2024-11-16T00:00:00+00:00 [running]> on host aa17a4cdcdc6
[2024-11-16T11:40:11.640+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_news' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-16T00:00:00+00:00'
[2024-11-16T11:40:11.651+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-16T11:40:11.654+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-16T11:40:11.656+0000] {logging_mixin.py:190} INFO - Current task name:run_API_news state:running start_date:2024-11-16 11:40:10.629170+00:00
[2024-11-16T11:40:11.658+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-16T11:40:11.659+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-16T11:40:11.856+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python3', 'C:/Users/33672/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI.py']' returned non-zero exit status 2.
[2024-11-16T11:40:11.857+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-16T11:40:12.019+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-16T11:40:12.023+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_news, run_id=scheduled__2024-11-16T00:00:00+00:00, execution_date=20241116T000000, start_date=20241116T114010, end_date=20241116T114012
[2024-11-16T11:40:12.071+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-16T11:40:12.074+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-16T11:40:12.075+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-16 11:36:24.052772+00:00
[2024-11-16T11:40:12.076+0000] {logging_mixin.py:190} INFO - Task hostname:aa17a4cdcdc6 operator:PythonOperator
[2024-11-16T11:40:12.153+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-16T11:40:12.268+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
