[2024-11-20T08:17:12.281+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T08:17:12.303+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: app_data_pipeline_fin.fetch_and_store_data scheduled__2024-11-19T16:00:00+00:00 [queued]>
[2024-11-20T08:17:12.313+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: app_data_pipeline_fin.fetch_and_store_data scheduled__2024-11-19T16:00:00+00:00 [queued]>
[2024-11-20T08:17:12.314+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2024-11-20T08:17:12.333+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_store_data> on 2024-11-19 16:00:00+00:00
[2024-11-20T08:17:12.341+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=222) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-20T08:17:12.345+0000] {standard_task_runner.py:72} INFO - Started process 224 to run task
[2024-11-20T08:17:12.345+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'app_data_pipeline_fin', 'fetch_and_store_data', 'scheduled__2024-11-19T16:00:00+00:00', '--job-id', '785', '--raw', '--subdir', 'DAGS_FOLDER/insert_data_fin.py', '--cfg-path', '/tmp/tmpye9m5un4']
[2024-11-20T08:17:12.347+0000] {standard_task_runner.py:105} INFO - Job 785: Subtask fetch_and_store_data
[2024-11-20T08:17:12.396+0000] {task_command.py:467} INFO - Running <TaskInstance: app_data_pipeline_fin.fetch_and_store_data scheduled__2024-11-19T16:00:00+00:00 [running]> on host e6bda0a190de
[2024-11-20T08:17:12.481+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='app_data_pipeline_fin' AIRFLOW_CTX_TASK_ID='fetch_and_store_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-19T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-19T16:00:00+00:00'
[2024-11-20T08:17:12.483+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T08:17:12.484+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T08:17:12.485+0000] {logging_mixin.py:190} INFO - Current task name:fetch_and_store_data state:running start_date:2024-11-20 08:17:12.304610+00:00
[2024-11-20T08:17:12.485+0000] {logging_mixin.py:190} INFO - Dag name:app_data_pipeline_fin and current dag run status:running
[2024-11-20T08:17:12.486+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T08:17:16.495+0000] {logging_mixin.py:190} INFO - Connexion à MongoDB fermée.
[2024-11-20T08:17:16.497+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-20T08:17:16.511+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T08:17:16.512+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=app_data_pipeline_fin, task_id=fetch_and_store_data, run_id=scheduled__2024-11-19T16:00:00+00:00, execution_date=20241119T160000, start_date=20241120T081712, end_date=20241120T081716
[2024-11-20T08:17:16.527+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-20T08:17:16.528+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-20T08:17:16.528+0000] {logging_mixin.py:190} INFO - Dag name:app_data_pipeline_fin queued_at:2024-11-20 08:09:50.078441+00:00
[2024-11-20T08:17:16.529+0000] {logging_mixin.py:190} INFO - Task hostname:e6bda0a190de operator:PythonOperator
[2024-11-20T08:17:16.578+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-20T08:17:16.597+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T08:17:16.600+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
