[2024-11-15T10:58:17.948+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-15T10:58:18.035+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_fin manual__2024-11-15T10:51:14.967678+00:00 [queued]>
[2024-11-15T10:58:18.068+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_fin manual__2024-11-15T10:51:14.967678+00:00 [queued]>
[2024-11-15T10:58:18.070+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-15T10:58:18.144+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_fin> on 2024-11-15 10:51:14.967678+00:00
[2024-11-15T10:58:18.179+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-15T10:58:18.183+0000] {standard_task_runner.py:72} INFO - Started process 407 to run task
[2024-11-15T10:58:18.185+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_fin', 'manual__2024-11-15T10:51:14.967678+00:00', '--job-id', '669', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmpxnaqis4q']
[2024-11-15T10:58:18.191+0000] {standard_task_runner.py:105} INFO - Job 669: Subtask run_API_fin
[2024-11-15T10:58:18.390+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_fin manual__2024-11-15T10:51:14.967678+00:00 [running]> on host aa17a4cdcdc6
[2024-11-15T10:58:18.673+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_fin' AIRFLOW_CTX_EXECUTION_DATE='2024-11-15T10:51:14.967678+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-15T10:51:14.967678+00:00'
[2024-11-15T10:58:18.678+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-15T10:58:18.680+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-15T10:58:18.681+0000] {logging_mixin.py:190} INFO - Current task name:run_API_fin state:running start_date:2024-11-15 10:58:18.037010+00:00
[2024-11-15T10:58:18.682+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-15T10:58:18.684+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-15T10:58:18.974+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python3', 'C:/Users/33672/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI_fin.py']' returned non-zero exit status 2.
[2024-11-15T10:58:18.975+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-15T10:58:19.014+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-15T10:58:19.015+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_fin, run_id=manual__2024-11-15T10:51:14.967678+00:00, execution_date=20241115T105114, start_date=20241115T105818, end_date=20241115T105819
[2024-11-15T10:58:19.059+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-15T10:58:19.060+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-15T10:58:19.061+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-15 10:51:15.125664+00:00
[2024-11-15T10:58:19.063+0000] {logging_mixin.py:190} INFO - Task hostname:aa17a4cdcdc6 operator:PythonOperator
[2024-11-15T10:58:19.119+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-15T10:58:19.148+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
