[2024-11-12T11:27:38.233+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-12T11:27:38.573+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-01T12:00:00+00:00 [queued]>
[2024-11-12T11:27:38.648+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-01T12:00:00+00:00 [queued]>
[2024-11-12T11:27:38.665+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-12T11:27:38.851+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_news> on 2024-11-01 12:00:00+00:00
[2024-11-12T11:27:39.006+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=97) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-12T11:27:39.011+0000] {standard_task_runner.py:72} INFO - Started process 133 to run task
[2024-11-12T11:27:39.044+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_news', 'scheduled__2024-11-01T12:00:00+00:00', '--job-id', '454', '--raw', '--subdir', 'DAGS_FOLDER/insert_data_fin.py', '--cfg-path', '/tmp/tmpi9hiv94w']
[2024-11-12T11:27:39.074+0000] {standard_task_runner.py:105} INFO - Job 454: Subtask run_API_news
[2024-11-12T11:27:49.149+0000] {cli_action_loggers.py:177} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-12T11:27:56.511+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_news scheduled__2024-11-01T12:00:00+00:00 [running]> on host 97974acde2c9
[2024-11-12T11:27:56.945+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_news' AIRFLOW_CTX_EXECUTION_DATE='2024-11-01T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-01T12:00:00+00:00'
[2024-11-12T11:27:56.983+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-12T11:27:56.985+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-12T11:27:56.987+0000] {logging_mixin.py:190} INFO - Current task name:run_API_news state:running start_date:2024-11-12 11:27:38.593396+00:00
[2024-11-12T11:27:56.988+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-12T11:27:56.992+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-12T11:27:57.185+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python3', '/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI.py']' returned non-zero exit status 2.
[2024-11-12T11:27:57.187+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-12T11:27:57.253+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-12T11:27:57.256+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_news, run_id=scheduled__2024-11-01T12:00:00+00:00, execution_date=20241101T120000, start_date=20241112T112738, end_date=20241112T112757
[2024-11-12T11:27:57.334+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-12T11:27:57.344+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-12T11:27:57.351+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-12 11:25:55.288752+00:00
[2024-11-12T11:27:57.361+0000] {logging_mixin.py:190} INFO - Task hostname:97974acde2c9 operator:PythonOperator
