[2024-11-18T08:28:26.641+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-18T08:28:26.770+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-17T18:00:00+00:00 [queued]>
[2024-11-18T08:28:26.791+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: add_data_API.run_API_news scheduled__2024-11-17T18:00:00+00:00 [queued]>
[2024-11-18T08:28:26.792+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-11-18T08:28:26.840+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_API_news> on 2024-11-17 18:00:00+00:00
[2024-11-18T08:28:26.911+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=128) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-18T08:28:26.914+0000] {standard_task_runner.py:72} INFO - Started process 138 to run task
[2024-11-18T08:28:26.918+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'add_data_API', 'run_API_news', 'scheduled__2024-11-17T18:00:00+00:00', '--job-id', '701', '--raw', '--subdir', 'DAGS_FOLDER/insert_data.py', '--cfg-path', '/tmp/tmp75lzbb9i']
[2024-11-18T08:28:26.921+0000] {standard_task_runner.py:105} INFO - Job 701: Subtask run_API_news
[2024-11-18T08:28:27.283+0000] {task_command.py:467} INFO - Running <TaskInstance: add_data_API.run_API_news scheduled__2024-11-17T18:00:00+00:00 [running]> on host 12f134266ead
[2024-11-18T08:28:27.751+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='add_data_API' AIRFLOW_CTX_TASK_ID='run_API_news' AIRFLOW_CTX_EXECUTION_DATE='2024-11-17T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-17T18:00:00+00:00'
[2024-11-18T08:28:27.761+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-18T08:28:27.763+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-18T08:28:27.764+0000] {logging_mixin.py:190} INFO - Current task name:run_API_news state:running start_date:2024-11-18 08:28:26.771282+00:00
[2024-11-18T08:28:27.767+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API and current dag run status:running
[2024-11-18T08:28:27.770+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-18T08:28:27.904+0000] {logging_mixin.py:190} INFO - Erreur lors de l'ex√©cution du script : Command '['python', 'C:/Users/33672/OneDrive/Documents/GitHub/Projet_EDD/script/getAPI.py']' returned non-zero exit status 2.
[2024-11-18T08:28:27.905+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-18T08:28:27.989+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-18T08:28:27.992+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=add_data_API, task_id=run_API_news, run_id=scheduled__2024-11-17T18:00:00+00:00, execution_date=20241117T180000, start_date=20241118T082826, end_date=20241118T082827
[2024-11-18T08:28:28.026+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-11-18T08:28:28.028+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-11-18T08:28:28.029+0000] {logging_mixin.py:190} INFO - Dag name:add_data_API queued_at:2024-11-18 08:11:46.809673+00:00
[2024-11-18T08:28:28.031+0000] {logging_mixin.py:190} INFO - Task hostname:12f134266ead operator:PythonOperator
[2024-11-18T08:28:28.077+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-18T08:28:28.108+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
